name: Deploy Gmail MCP server

on:
  push:
    branches:
      - main
   
jobs: 
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: SSH Setup and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e

            #Install System Dependencies
            sudo apt update && sudo apt upgrade -y
            sudo apt install -y python3 python3-pip python3-venv nginx snapd git
            sudo snap install core; sudo snap refresh core
            sudo snap install --classic certbot
            sudo ln -sf /snap/bin/certbot /usr/bin/certbot

            #Clone or Update Repository
            if [ ! -d "/home/ubuntu/Gmail-MCP" ]; then
              git clone https://github.com/PeterAkande/gmail_mcp.git /home/ubuntu/Gmail-MCP
            else
              cd /home/ubuntu/Gmail-MCP
              git pull origin main
            fi

            #Set up Python Virtual Environment
            cd /home/ubuntu/Gmail-MCP
            python3 -m venv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt

            #Set up Systemd Service
            ServiceFile=/etc/systemd/system/Gmail-MCP.service
            sudo bash -c "cat > $ServiceFile" << EOL
            [Unit]
            Description=Gmail MCP Service
            After=network.target

            [Service]
            User=ubuntu
            WorkingDirectory=/home/ubuntu/Gmail-MCP
            ExecStart=/home/ubuntu/Gmail-MCP/venv/bin/python main:app --host 0.0.0.0 --port 8000
            Restart=always

            [Install]
            WantedBy=multi-user.target
            EOL

            sudo systemctl daemon-reload
            sudo systemctl enable Gmail-MCP
            sudo systemctl restart Gmail-MCP

            #Configure Nginx
            NginxFile=/etc/nginx/sites-available/Gmail-MCP
            sudo bash -c "cat > $NginxFile" << EOL
            server {
                
                server_name your_domain_or_ip;

                location / {
                    proxy_pass http://127.0.0.1:8000:
                    proxy_set_header Host \$host;
                    proxy_set_header X-Real-IP \$remote_addr;
                    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
                    proxy_set_header X-Forwarded-Proto \$scheme;
                }
            }
            EOL

            sudo ln -sf /etc/nginx/sites-available/Gmail-MCP /etc/nginx/sites-enabled/
            sudo nginx -t
            sudo systemctl reload nginx

            #Install Certbot for SSL certificate
            sudo snap install core
            sudo snap refresh core
            sudo snap install --classic certbot
            sudo ln -s /snap/bin/certbot /usr/bin/certbot || true
            sudo certbot --nginx -d your_domain_or_ip --non-interactive --agree-tos -m myemail.gmail.com